clashofclans:
  api:
    url-getClanMembersList: "https://api.clashofclans.com/v1/clans/"
    bearer-token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjNiOTYyNzMxLWZmYzItNGU5Mi05MTExLTQxMWU3N2UxYTBlZSIsImlhdCI6MTc1NzU0NzQwMiwic3ViIjoiZGV2ZWxvcGVyL2EwODJkMGU5LTVjNDQtMmVlMi1hY2ZlLTBlN2E4MzEyNjM4NyIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3OS4yMDkuMTQyLjM4Il0sInR5cGUiOiJjbGllbnQifV19.ym5oYSeJhCOyHleTmzh9SBQadISzlU5GAMR6VYWFMNsctxoimxmIll2udj3-cFlBtKGGTdZc1R0HY8EcvFBacg"
  endpoints:
    clan-capital-raid-seasons: "https://api.clashofclans.com/v1/clans/tag/capitalraidseasons"
    clan-members: "https://api.clashofclans.com/v1/clans/tag/members"
    clan: "https://api.clashofclans.com/v1/clans/"
    clan-war-league-group: "https://api.clashofclans.com/v1/clans/tag/currentwar/leaguegroup"
    clan-wars-league: "https://api.clashofclans.com/v1/clanwarleagues/wars/tag"

